# Generated by Django 5.1.5 on 2025-02-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0038_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
