# Generated by Django 5.1.5 on 2025-02-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0040_remove_examparticipant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctoringevent',
            name='user',
        ),
    ]
