# Generated by Django 5.1.5 on 2025-02-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0041_remove_proctoringevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='response',
        ),
    ]
