# Generated by Django 5.1.5 on 2025-02-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_series', '0043_admissionreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionReview',
        ),
    ]
