# Generated by Django 5.1.5 on 2025-02-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0141_remove_visitor_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job1',
            name='job_status',
            field=models.CharField(max_length=50),
        ),
    ]
