# Generated by Django 5.1.5 on 2025-02-10 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0142_alter_job_job_status_alter_job1_job_status'),
        ('login', '0027_new_user_agreed_to_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_user_enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(default='+91', max_length=3)),
                ('mobile_number', models.CharField(max_length=15)),
                ('course', models.CharField(default='N/A', max_length=128)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.new_user')),
            ],
        ),
    ]
