# Generated by Django 5.1.5 on 2025-02-11 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0143_new_user_enquiry'),
        ('login', '0027_new_user_agreed_to_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user_enquiry',
            name='university_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.universityincharge'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='job1',
            name='job_status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
