# Generated by Django 5.1.5 on 2025-02-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0144_new_user_enquiry_university_in_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user_enquiry',
            name='collegeName',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
