# Generated by Django 5.1.5 on 2025-02-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_alter_admissionreview_agree_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionreview',
            name='agree_terms',
            field=models.BooleanField(default=True),
        ),
    ]
