# Generated by Django 5.1.5 on 2025-02-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_admissionreview1_graduation_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionreview1',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
